### ISSUE TITLE
hi, may ask differences between safetensors vs flatbuffer?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/safetensors#145]
Since it looks like both of them are data store library. But flatbuffer not only can store Tensor, but also structures && many customized data types. Does safetensors also able to?

Furthermore, does safetensor able to using cross platform with a very tiny dependency lib? such as use it on Android or iOS

**Comment by Narsil** [comment]
Hi, Thanks for the question.

I did check out flatbuffers before writing this.
The first thing is that flatbuffers requires a custom file and generate code, which in my personal experience incur a big overhead in terms of code management (and now everyone has to rely on flatbuffers libraries).

There is no need to store complex datastructures for saving machine learning (deep) models. Tensors are enough in pretty much 100% of the cases I am aware of. So avoiding an extra dependency because we don't need the complexity is always good IMO.

For instance you don't need this library to read safetensors files. https://gist.github.com/Narsil/3edeec2669a5e94e4707aa0f901d2282 so you can read those files without any extra dependency. 
This lib exists because it provides a few added features like loading speed and loading only slices of some tensors (which is required in multi GPU setup, so not your everyday need).

Does this answer your question ?

**Comment by jinfagang** [comment]
thank u for your answer, I now realize that flatbuffer more like provide a `datastructure` function which can be crossplatform and calling in many language, this is not like  just a binary data format.

**Comment by thelou1s** [comment]
So, does safetensor able to using cross platform(android and ios)? Yes or No?
