### ISSUE TITLE
Question about parallelism/rayon

### ISSUE THREAD

**Issue by mishig25** [huggingface/safetensors#15]
Questions regarding parallelism:

1. If I'm not mistaken, both tensor serialization & deserialization operations should be parallelizeable. Is this assumption correct? For example, I was thinking this line below can be replaced with [par_extend](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelExtend.html#tymethod.par_extend) https://github.com/huggingface/safetensors/blob/86e356fed6b75d4b0a06ee446ab94f1317eafc2e/safetensors/src/tensor.rs#L59 
2. If point 1 is valid, does it make sense to do so? Or is it not worth it (i.e. speed up might not be great OR we don't want to introduce dependency on rayon)?

Thanks so much! 🤗 
cc: @Narsil

**Comment by Narsil** [comment]
Hi @mishig25 ,

Have you tried it ? I'm curious to see the results.

Since `buffer` is mutable I expect this will not be trivially parallelizable. 
It's probably technically doable in this function since all buffer sizes are known at this point.

For writing to disk `serialize_file` I anticipate, the limiting factor would be the actual disk speeds not CPUs, and random disk access is I think worse than serialized one even for SSDs. 

`rayon` is a big dependency and I wouldn't add it without solid reason. One of the biggest merits of this lib is the smallish size and very low dependencies (currently only `serde` and `serde_json`).
