### ISSUE TITLE
Is it possible to make plain_convert.py like removing huggingface_hub inside convert.py

### ISSUE THREAD

**Issue by camenduru** [huggingface/safetensors#150]
Please make your tools like LEGO pieces, like plain_convert.py, so that developers can use them wherever they want with freeeeeeedooooooom 🐱‍🏍😋

**Comment by camenduru** [comment]
I want to add `safetensors to diffusers` here https://huggingface.co/spaces/camenduru/converter

**Comment by Narsil** [comment]
Hi thanks for your suggestion. The depency on `huggingface_hub` (and `transformers`) library is by being overly explicit in what we're trying to do.

A regular `convert.py` should be really just:
```python
import torch
from safetensors.torch import save_file
weights = torch.load(filename)
save_file(weights, "model.safetensors")
```
(Ofc this should be adapted for other libraries than `torch`.)

BUT 

this might lead to bigger files than necessary because of tensors with different names pointing on the same data which safetensors doesn't allow.  (This may or may not be relaxed but for now this property makes understanding the files and how loading works much easier) 
The extra dependencies (here `transformers`) makes sure that we can safely remove the extra duplicated tensors and that the model being used is not broken (it could be if there was some bug in transformers model config that would not be able to make the same tensors, actually the same tensors for instance, biggest culprit is usually word_embeddings and `lm_head` that share the matrix in most LM).

If you check out the logic you'll see that  `huggingface_hub` is only used to see what is on the hub, and create the PR automatically (stuff which can't realistically be done without it).

Couldn't you just use  the `convert_file` function for instance ?
This function should be the lego piece you're looking for, no ?

Just as a note: there's a reason `convert.py` is not actually in the library, and the reason is that it's not possible "in general" to convert any torch files to safetensors, since it cannot actually contain custom code, or nested dicts, or nested tensors etc... 
So `convert.py` is just meant as showcasing on how to do it (and the subtleties involved which I explained here).

**Comment by camenduru** [comment]
thanks for the info @Narsil ❤  ok I will use `convert_file`  please teach me what is the `shared_pointers` part doing 

```py
shared = shared_pointers(loaded)
for shared_weights in shared:
    for name in shared_weights[1:]:
        loaded.pop(name)
```

```py
def shared_pointers(tensors):
    ptrs = defaultdict(list)
    for k, v in tensors.items():
        ptrs[v.data_ptr()].append(k)
    failing = []
    for ptr, names in ptrs.items():
        if len(names) > 1:
            failing.append(names)
    return failing
```

**Comment by Narsil** [comment]
This is what I'm alluding to above.

PyTorch can use the same buffer to have 2 distinct tensors.

```python
import torch

A = torch.ones((10, 10))
B = A[:]
C = A[0]

print(A.data_ptr(), B.data_ptr(), C.data_ptr())
```
All pointers are the same.

If you are to save those 3 tensors on disk using `torch.save` what will happen is that there is going to be one buffer containing A data, and both B and C will link to it instead, meaning if you modify A, you're also going to modify both B and C.
```python
A[0, 0] = 0
print(B[0, 0])  # 0
print(C[0])   # 0
```

 It's fine and dandy when you control your code and allows to prevent some copying of data, but it's quite confusing when using this data within a model (since two different tensors could actually link to the same tensor). Not to mention, that there is no support for this kind of thing within Tensorflow and Jax (afaik).
 It also means that it's easy to create bugs when using those files (when you don't realize this) because you could "break" some logic if you ever clone those tensors.
 
 In order to prevent this, by default `safetensors.torch.save_file` will duplicate them meaning they would be now distinct tensors (making everything extra explicit and usable from other frameworks). This will work, but can lead to extra space being taken on disk. 
 
In addition to slight breaking when fine-tuning models, since now the tensors wouldn't be shared. This bug wouldn't happen in `transformers` since the tensors are forced shared after model loading (it's called `tie_weights` method if you're interested), but it could on custom code.
 
 So this `shared_pointers` code, removes such "duplicate" tensors (so no extra space). It also verifies that `transformers` is able to correctly reload the model and properly do the `tie_weights` (that would be a bug in `transformers` but we don't want to create non functional files if possible).
 `diffusers` and `StableDiffusion` don't have this issue afaik since there's no shared tensors.
 
 Does this answer your question ?

**Comment by camenduru** [comment]
Yes, thanks @Narsil ❤ I need to study transformers more 🙄
