### ISSUE TITLE
Good use case for Apache Arrow?

### ISSUE THREAD

**Issue by stevenbedrick** [huggingface/safetensors#16]
Hello! I love the motivation behind saftensors, and was wondering if y'all had thought about using Apache Arrow for the byte-buffer part of things. It would bring a lot of cross-platform/architecture compatibility in, works great with very large amounts of data, and has some standards for storing multidimensional tensors (both dense and sparse): https://arrow.apache.org/docs/format/Other.html

Anyway, I'm sure it's already been suggested, but just in case, I wanted to bring it to your attention!

**Comment by Narsil** [comment]
Hi @stevenbedrick ,

This is a very good comment, I personally didn't check initially when I looked into this issue.
Now that this repo is being examined more carefully, it definitely popped up internally. 
I need to check more carefully, because we also use `datasets` which do depend on `arrow`.
If `transformers` could have less dependencies instead of more that would be great.

I'm pretty sure one of the culprits to cover everything needed is going to be `bfloat16` support (which is being more used nowadays for large models). 
It doesn't seem huge, but `h5` doesn't support it either and the issues about it seem old, jax had to fork numpy for this: https://github.com/google/jax/pull/1720/files#diff-5203ef9a5a6bbd4a0a11baea4cda0215e5396ffd4d73296eab73dd14262b79f9R15

The other thing is that both `h5` and `arrow` are (200k and 400k+) lines of cpp code. It feels like a lot and that there's bound to be some flaw in it like buffer overflows. 
Arrow only displays 2 CVE from 2019. Either it's not getting enough attention, or it's a super impressive feat !

Not to say that this current attempt is perfect by any means, but less features/less code means more auditable. And rust should prevent buffer overflows. It definitely caught some bad indexing I did for loading tensor slices.
The dependencies might use `unsafe` and have flaws that's also why they are kept at a minimum, and the bindings might also create risk for sure.
The spec being so simple you probably can also rewrite a saver/writer directly in another language in a very few amount of lines.

**Comment by stevenbedrick** [comment]
I totally agree with keeping things simple and having less dependencies, for sure. My thought was more about re-using an existing serialization format (one that is designed for very efficient I/O etc.), and being able to piggyback on all of their tooling, testing, etc.- not to mention the instant zero-cost interop with everything else that can handle Arrow (so lots of databases, analytics tools, etc.). The point about bfloat16 is a very good one, though, as I don't see that Arrow can store those at the moment (but I could be wrong about that).

As far as security issues from depending on cpp code, that's certainly a worthwhile concern!! I do know that Arrow is under extremely active and ongoing development and is used as a low-level and core component of a ton of other libraries and tools, so hopefully that means that it is one of those "many eyes, shallow bugs" situations. I don't know much about the security engineering situation in the Arrow-verse, though I would certainly trust _their_ I/O code more than anything I might hand-roll... 😆 

Anyway, it is definitely one of those "pick your poison" engineering tradeoff situations!

**Comment by Narsil** [comment]
> As far as security issues from depending on cpp code, that's certainly a worthwhile concern!! I do know that Arrow is under extremely active and ongoing development and is used as a low-level and core component of a ton of other libraries and tools, so hopefully that means that it is one of those "many eyes, shallow bugs" situations. I don't know much about the security engineering situation in the Arrow-verse, though I would certainly trust their I/O code more than anything I might hand-roll... laughing

https://heartbleed.com/

This is a bug in OpenSSL that's used pretty much everywhere in the web and it was there for quite a while. So no being a "core" library does not unfortunately means that there's auditing being done on even a comparable level to the criticity of the library.
400k lines of CPP without any major flaw (read arbitrary code execution) would be unheard of to me.
