### ISSUE TITLE
Might not related but wanna ask: does there can have a c++ version?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/safetensors#222]
Hello, wanna ask 2 questions:

1. will safetensors provides a c++ version, it looks more convenient then pth or onnx;
2. does it possible to load safetensors into some forward lib not just pytorch, such as onnxruntime etc?

**Comment by Narsil** [comment]
1. Thanks, @mfuntowicz actually coded some loader in C++ if I'm not mistaken.

Not sure about creating bindings for Rust here, since the FFI with C++ is always a bit messy and it should be relatively straightforward to implement a loader in any language.
If we did, it would probably be a C export. However, making sure C-bindings are safe is not something I feel confident about doing right now.

2. 

Sure, this lib provides tensorflow, numpy, torch, paddle, jax already.
onnxruntime probably cannot be dropped in, since `onnx` files also contain the graph of the model.

But here's a snippet showing how to export from ONNX to this format: https://github.com/huggingface/safetensors/issues/188

I could look into how to load if you want, but in order to be efficient you would need a way to load the graph and the weights separately, and I'm not sure there's an easy primitive for that.

**Comment by Narsil** [comment]
Provided by @mfuntowicz :¨

Would that work: 

https://gist.github.com/Narsil/5d6bf307995158ad2c4994f323967284 

?

**Comment by SomeoneSerge** [comment]
C bindings should be more than adequate, and I also think they're a bit of a "must" if wider safetensors adoption is a desirable thing. I don't know what your (owners') priorities are, and I'm also unfamiliar with rust, but I see three possible levels of upstream support and I'd appreciate either

- [ ] Marking the relevant functions with `extern "C"`. AFAIU, this should already allow users to build .a/.so libraries
- [ ] Maintaining the headers upstream
- [ ] Ensuring the library can be located by "normal" means (CMake, pkg-config)

**Comment by mfuntowicz** [comment]
Hi @lucasjinreal, 

I've been working on adding a C-API binding lately, please don't hesitate to have a look: https://github.com/huggingface/safetensors/pull/259
