### ISSUE TITLE
Comparison with "Advanced Scientific Data Format"

### ISSUE THREAD

**Issue by AlexanderVanEck** [huggingface/safetensors#263]
Hello HuggingFace team 👋 ,

Thank you for this amazing contribution, the field can surely use newer and robust ways of storing tensors 🙇 
Could you please shed some light on the comparison of SafeTensors vs. using the asdf file format? We have seen some success with this file format and would like to understand how it stacks up against SafeTensors (especially within the features comparison).

Many thanks, Alexander

**Comment by Narsil** [comment]
I'm supposing you're referring to : https://asdf-standard.readthedocs.io/en/1.0.3/

I didn't know that format, I read briefly, and from what I read both are trying to solve very different problems.

Asdf is trying to be hierarchical, has references, endian ordering and works on blocks which I guess is for faster editing of the file.

On the other hand, `safetensors` is MUCH simpler.
Everything is *flat*, there's only `little-endianness`. Tensors only have `dtype` and `shape`, there's no nesting and no blocks.
It also aims to be highly focused for ML which is the reason for the presence of `BFloat16`  which is a format that to my knowledge is quite specific to the field (and GPUs).

Simplicity provides some benefits because of the no endianness support, we can safely zero-copy every file (most machines are little-endian, if you have a big endian machine, you will have to copy).
And because of the flat layout it's rather trivial to parse (ML doesn't require to manipulate complex objects, everything is tensors).

That's my fast reading interpretation of the docs, more knowledgeable people would probably correct me.

Closing this. Feel free to reopen if there's still some unanswered question.
