### ISSUE TITLE
Cannot save more than 1 empty pyTorch tensor in a safetensors file.

### ISSUE THREAD

**Issue by leandro-gracia-gil** [huggingface/safetensors#280]
### System Info

Safetensors 0.3.1. Other details are not really relevant as explained below.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

Just try to save 2 empty tensors as you would do following the official examples.

```python
import torch
from safetensors.torch import save_file

tensors = {
    'foo': torch.tensor([]),
    'bar': torch.tensor([]),
}

save_file(tensors, 'test.safetensors')
```

### Expected behavior

Since empty tensors are supported, this should work normally. In fact, saving _just one_ empty tensor works.

But when saving more than one empty tensor you get this:
> RuntimeError: 
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'foo', 'bar'}].
            A potential way to correctly save your model is to use `save_model`.
            More information at https://huggingface.co/docs/safetensors/torch_shared_tensors

The reason is that the return value of the storage_ptr method from bindings/python/py_src/safetensors/torch.py is being used to determine if tensors share memory, but in the case of empty tensors the returned value is always 0. Which makes sense, because no memory is being allocated. But this means that once you have more than a single empty tensor the library thinks that they are sharing memory and raises a runtime exception.

Empty tensors should be excluded from this shared memory check, or at least multiple tensors with a storage_ptr of 0.

**Comment by Narsil** [comment]
Would you care to elaborate why you need many empty tensors in the first place ?
Having context usually helps finding better solutions.

Unallocated tensors (device meta) are for instance banned, and not allowed (even though we could happily save empty tensors instead). And the reason is that storing device meta is usually just a bug, never really an intent.

Here I'm struggling to understand why saving empty tensors is actually a desirable feature.

**Comment by leandro-gracia-gil** [comment]
> Would you care to elaborate why you need many empty tensors in the first place ?

Sure. I'm using safetensors as the way to save tensors in a dataset, then read from them as part of my input pipeline. With this I mean saving training data, not necessarily model weights. Though from the safetensors perspective it's all just tensors.

What is happening is simply that some of the training data tensors have variable lengths across some axis depending on their content, and while normally these tensors are not empty, there are some cases where their variable length is zero. If this happens with 2 or more different tensors at the same time, you hit this bug.

> Here I'm struggling to understand why saving empty tensors is actually a desirable feature.

It is already a supported feature. You can currently save and load empty tensors from safetensors, and these tensors are supported by multiple frameworks such as pyTorch or TensorFlow. It only fails when you try to save more than one in the same file because it mistakenly complains about these tensors having shared memory, since the address for both is 0.

This is not really a new feature request. It's a bug about misdetecting shared memory use.

**Comment by leandro-gracia-gil** [comment]
Sorry, I misread your initial reply. So you say that being currently able to save and load empty tensors is actually a bug, not really a supported feature.

In that case I'd suggest to either:
- If they should not be supported, clearly document this limitation and explicitly disable saving empty tensors. Currently there is nothing saying that you can't, nothing to make you think it shouldn't work, and if you try it, it works (for 1 tensor at least). In this case I will look for some other alternative to save my tensor data.

- If the use case of using safetensors to store general tensor data is considered reasonable, or if it's ok to support more complex models that might have empty weights in their state dict (for example, where one dim is based on some hyperparameter that can be set to 0), then please fix support for them.

I would of course prefer the second approach, so I can still use this library. But besides that I think it makes sense to support empty tensors simply because it's a completely valid kind of tensor. This is the kind of thing that is likely to bite back at some point for one reason or another.

**Comment by Narsil** [comment]
> Sorry, I misread your initial reply. So you say that being currently able to save and load empty tensors is actually a bug, not really a supported feature.

Not exactly what I said. Saving empty/loading empty tensors is supported and works correctly (in the Rust crate).
Here we're only talking about the `torch` layer, where we can make different decisions based on what torch does:

## 1
```python
save_file({"B": torch.zeros((10, 10), device=torch.device("meta")}, "test.safetensors")
# NotImplementedError: Cannot copy out of meta tensor; no data!
```
However saving empty files is really **supported** currently:
## 2
```python
import torch
from safetensors.torch import save_file

A = torch.zeros((10, 10))
D = torch.zeros((10, 10))
B = A[:0]
C = D[:, :0]

save_file({"B": B, "C": C}, "test.safetensors")
```
Works perfectly fine, and the file results in being empty (which is a shame).

Now the question at hand is of `torch.tensor([])`.
## 3
```python
  import torch
  from safetensors.torch import save_file

  A = torch.tensor([])
  B = torch.tensor([])

  save_file({"A": A}, "test.safetensors")
  print("Single OK")
  save_file({"A": A, "B": B}, "test.safetensors")  # Not OK
```

I agree that the inconsistency is not OK. However, I'm tending to think that this is closer to `device("meta")` than the 2nd example.
Therefore, I would think having a proper error in that case would be nice (the issue is not the sharing it's the emptiness).

Note: 
## 4
```python
import torch
from safetensors.torch import save_file

A = torch.zeros((10, 10))
B = A[:0]
C = A[:, :0]

save_file({"B": B, "C": C}, "test.safetensors")  # Not OK
```
This example does *not* work, but it's not about having empty tensors, it's that both actually do share some storage (A storage).
The fact that these tensors are empty has nothing to do with it. If they were not empty, they would still share storage.
`safetensors` does not try to reason about the underlying tensors to see if the slices are actually disjoint and continuous or not (and I'm not sure it should).
In that case, if you *know* both are disjoint, it's relatively easy to call `.clone()` on your tensors (creating new storage for each, potentially duplicating if your tensors are not actually disjoint).

**Comment by leandro-gracia-gil** [comment]
I see, thanks for the detailed examples.

My use case is not an empty slice of a tensor, but a tensor created from a list that for some particular data happened to be empty (example 3). In that case calling `.clone()` does not help. It is also not an empty file either, as there will be multiple other non-empty tensors.

I would argue that if some forms of empty non-fake tensors are supported (example 2), then other forms (example 3) should be supported too for consistency. Most users won't even be aware of the internal difference of whether memory is allocated or not. They will just find that it fails and think empty tensors are not supported, then possibly proceed to file a bug / feature request.

If you finally decide to raise an error in example 3 instead of supporting it, could you tell me some workaround I could use? As I said, `.clone()` won't work here. If possible I'd strongly prefer not having to do things like detect empty lists, make them not empty, create a tensor, then slice them empty again for every tensor that could possibly be empty.

**Comment by Narsil** [comment]
> I would argue that if some forms of empty non-fake tensors are supported (example 2), then other forms (example 3) should be supported too for consistency. 

Form 1 is the same and yet not accepted.
1/ The reason is that 1 is really erroring out because `torch` errors out when we're trying to access the internal buffer before saving.
2/ is really not accepted by design, it's more a consequence of the code (B and C do not share storage, they are contiguous, therefore saving is OK).
3/ is behaving that way yet it was never really looked at, it's a consequence of all the other checks.

> a tensor created from a list that for some particular data happened to be empty (example 3)

I see. I'll go with ignoring those then.

**Comment by leandro-gracia-gil** [comment]
> I see. I'll go with ignoring those then.

Does that mean that I can save these empty tensors (like in example 3), load them later and still get empty tensors? Or are they going to be skipped entirely in the file, so that trying to load them with `get_tensor()` will fail? If it's the latter, I will need some kind of workaround because a tensor is expected to be there. It won't be empty in all my training samples.

**Comment by Narsil** [comment]
It will be saved empty.

**Comment by leandro-gracia-gil** [comment]
I see. Thank you very much! I think that should solve my problem.

One more question if you don't mind. This is not something I need or anything at the moment, just wondering. Is the empty tensor shape preserved? Like for example, an empty tensor that has multiple dims but only one or some are zero. Would the empty tensor you load preserve the original shape?

**Comment by Narsil** [comment]
Yes shapes are preserved. It's just like in `torch` or `numpy`.
