### ISSUE TITLE
Writing files > RAM

### ISSUE THREAD

**Issue by wouterzwerink** [huggingface/safetensors#291]
### Feature request

A (documented) method for writing files with more tensor data than can be fit into RAM

### Motivation

The documented method for writing files is to pass a dict of tensors. This requires having all the tensors in RAM.
However, it should be possible to write safetensors files larger than RAM by either adding tensors to existing files (without reading the files into memory).

That will enable some code like (function names are just to explain, could be different):
```python
safetensors.extend_file(tensors, filename)

# Alternatively, writing in chunks
with safetensors.create_file(filename) as s_file:
    for i in range(len(indices)):
         # Only one tensor loaded in RAM at a time
         s_file.write(create_tensor(i))
```

### Your contribution

Won't be able to work on this myself for a while. If this doesn't get picked up, I'll try implement this in a few weeks

**Comment by Narsil** [comment]
It's trickier than you think.

We need ALL metadata to be able to write the header. Since the data comes *after* the metadata, you cannot write the first tensors before having the entire header.

Making the API for such a thing relatively confusing (also lots of sanity checking because you need to write the proper tensors at every proper location, and not miss tensors for your final file to be correct.

Is there any reason you cannot just split the tensors over multiple files ? (This is what we do in distributed training for instance).
Fusing existing on disk files is much much simpler (just take all headers, add offsets whereever they might need to be, and copy the buffers next to each other in the new file (for which you can require as low ram as you want).

**Comment by akx** [comment]
Well, you can in fact stream a safetensors file to disk so long as you have a good guesstimate of the length of your header and reserve space for it in advance. You'll just need to pad the JSON with whitespace at the end; `serde` chokes on null bytes, but not spaces...

```python
import json
import random
import struct

import safetensors.torch

header_size = 65536
data_start_offset = header_size + 8
header = {}
filename = "test.safetensors"
with open(filename, "wb+") as f:
    f.seek(data_start_offset)
    for x in range(3):
        data = random.randbytes(4 * 4)
        start = f.tell() - data_start_offset
        header[f"tensor-{x}"] = {"dtype": "U8", "shape": [4, 4], "data_offsets": [start, start + len(data)]}
        f.write(data)
    f.seek(0)
    f.write(struct.pack("<Q", header_size))
    header_bytes = json.dumps(header).encode()
    assert len(header_bytes) < header_size
    f.write(header_bytes.ljust(header_size))
print(safetensors.torch.load_file(filename))
```
happily prints out
```
{'tensor-0': tensor([[ 16, 220, 170, 117],
        [202, 128,  68, 122],
        [ 70, 210,  61, 194],
        [177, 196, 130, 206]], dtype=torch.uint8), 'tensor-1': tensor([[ 32, 147,  97, 129],
        [147,  24, 193, 143],
        [241, 122, 232, 210],
        [245,  99,  79,  27]], dtype=torch.uint8), 'tensor-2': tensor([[ 74, 117, 201, 217],
        [ 27,  57,  60, 128],
        [136,  15, 230, 158],
        [ 47, 220, 168, 159]], dtype=torch.uint8)}
```

**Comment by Narsil** [comment]
That works ! 

However I wouldn't be ok implementing that in the core library because the failure mode when not enough space has been reserved is a pretty bad experience (and it's not easy to determine how much space you need without knowing all the tensors you need).
Futhermore, reserving way too much space is likely to occur and therefore that's a lot of wasted space for everyone if that becomes the standard.

Feel free to use that trick, it does work, but I'm not sure I would want to add such a surface in the lib without strong motivation.

**Comment by akx** [comment]
Yeah, it's a Weird Trick alright, but as discussed in the linked PR, I think allowing trailing whitespace padding for the header will be a good idea in the long run. (But that discussion is there :) )
