### ISSUE TITLE
Any plan to support Nvidia GPUDirect Storage?

### ISSUE THREAD

**Issue by carmark** [huggingface/safetensors#299]
### Feature request

Nvidia GPUDirect Storage has better performance to load model from NVMe disk or supported distributed storage. It will do the real `zero copy`.

### Motivation

It will get better performance with Nvidia GDS.

### Your contribution

Not sure.

**Comment by Narsil** [comment]
Definitely something we're looking at !

There's no pure Python GPUDirect Storage implementation to the best of my knowledge, so currently waiting on PyTorch for this a bit.
If there's a way to short-circuit PyTorch to enable this faster, I'm all up for it.
Non Python world users should already be able to leverage it, since the Rust code doesn't actually deal with where the memory is coming from so you can really have a memory mapped file and use GPUDirect Storage all the contents on the CPU at once.

**Comment by carmark** [comment]
The GPUDirect Storage of Nvidia has `cuFile` SDK to provide basic usage, such as `cuFileRead` and `cuFileWrite`.  I do not think there is pure Python implement.

**Comment by antferdom** [comment]
I have been conducting several experiments with GPUDirect through cuFile Python bindings provided by [rapidsai/kvikio](https://github.com/rapidsai/kvikio/tree/6d5bf9d1b41c228ef2ce37a2ba5a08a696e16cf0). The target motivation was to profile how by-passing the CPU memory could speedup big checkpoints allocation to GPU, thus achieving zero-copy loading.
We performed several micro-benchmarking using [fio](https://github.com/axboe/fio/tree/a142e0df6c1483a76d92ff7f9d8c07242af9910e) in order to trigger  libcufile, thus measuring theoretical maximum bandwidth. Nevertheless, those experiments were launched within a VM, so not formal results yet. One fio config used as example: 
```
# Example libcufile job, using cufile I/O
#
# Required environment variables:
#     GPU_DEV_IDS : refer to option 'gpu_dev_ids'
#     FIO_DIR     : 'directory'. This job uses cuda_io=cufile, so path(s) must
#                   point to GPUDirect Storage filesystem(s)
#
[global]
ioengine=libcufile
directory=${FIO_DIR}
gpu_dev_ids=${GPU_DEV_IDS}
cuda_io=cufile
direct=1
bs=1m
size=4g
numjobs=82
thread

[read-tensor]
rw=randread
```

**Results**
```bash
Run status group 0 (all jobs):
   READ: bw=3115MiB/s (3266MB/s), 38.0MiB/s-41.9MiB/s (39.8MB/s-43.9MB/s), io=328GiB (352GB), run=97741-107824msec

Disk stats (read/write):
  vda: ios=450476/970, sectors=687693824/11024, merge=0/311, ticks=11387018/57017, in_queue=10526996, util=99.48%
```
The above micro-benchmark tries to emulate the loading of Falcon-180B (82 chunks of **4.4GB** each). Deserialization overhead is omitted, since we are working with cupy arrays. Nevertheless these have `__cuda_array_interface__`, so **zero-copy** data exchange between CuPy and PyTorch can be achieved at no cost.

I would be highly interested in exploring this idea with safetensors as serialization/deserialization targets for the state_dict using GPUDirect. What do you think @Narsil ?

**Comment by Narsil** [comment]
Not sure if I read this correctly. The first number suggests reading at 3GB/s (insane) the second 38MiB/s (which doesn't really look good).

Which is it ? I'm going to try and setup something in candle/cudarc as it seems easier given the low level access to those APIs.

**Comment by antferdom** [comment]
Once all jobs are finished, here we are spawning threads and not process to not oversubscribe to the GPU and make `cudaMalloc` crash, the group statistics are printed.

From the [fio HOWTO repo notes] (https://github.com/axboe/fio/blob/a142e0df6c1483a76d92ff7f9d8c07242af9910e/HOWTO.rst#L2643)
**bw**
> Aggregate bandwidth of threads in this group followed by the minimum and maximum bandwidth of all the threads in this group. Values outside of brackets are power-of-2 format and those within are the equivalent value in a power-of-10 format.

With a lower quantity of threads:
```fio
[global]
ioengine=libcufile
directory=${FIO_DIR}
gpu_dev_ids=${GPU_DEV_IDS}
cuda_io=cufile
direct=1
bs=1m
size=4g
numjobs=16
thread

[read-tensor]
rw=randread
```

**Output:**
```bash
Run status group 0 (all jobs):
   READ: bw=2613MiB/s (2740MB/s), 163MiB/s-181MiB/s (171MB/s-190MB/s), io=64.0GiB (68.7GB), run=22596-25078msec

Disk stats (read/write):
  vda: ios=86014/479, sectors=134213632/5184, merge=0/171, ticks=492865/5535, in_queue=297040, util=97.62%
```
As a result, the bandwidth per thread increases.

You can also use [gdsio](https://docs.nvidia.com/gpudirect-storage/configuration-guide/index.html) as micro-benchmarking utility instead of fio.

Regarding access to `cuFile` APIs, [rapidsai/kvikio](https://github.com/rapidsai/kvikio/tree/6d5bf9d1b41c228ef2ce37a2ba5a08a696e16cf0) & [cupy](https://github.com/cupy/cupy/tree/5c32e40af32f6f9627e09d47ecfeb7e9281ccab2) provide Python binding, but maybe even lower level access is desired.

For example: 
```python
# %%
import cupy
import kvikio
import numpy as np
import torch
# %%
# kvikio write example
a = cupy.arange(100)
f = kvikio.CuFile("test_file", "w")
# Write whole array to file
f.write(a)
f.close()
# %%
"""
PyTorch also supports __cuda_array_interface__
zero-copy data exchange between CuPy and PyTorch can be achieved at no cost. 
"""
a = torch.rand((4,4), device="cuda")
b = cp.asarray(a)
logger.info(f"Tensor a: {a}")
logger.info(f"Tensor b: {b}")
# check the underlying memory pointer is the same
assert a.__cuda_array_interface__['data'][0] == b.__cuda_array_interface__['data'][0]
# %%
# convert a cupy array to torch tensor
a = cp.arange(10)
b = torch.as_tensor(a, device="cuda")
b += 1
print(f"Tensor b: {b}")
print(f"Tensor a: {a}")
```

**Comment by keepdying** [comment]
pytorch just landed prototype for gpudirect loading with an api wrapping cufile
https://docs.pytorch.org/tutorials/prototype/gpu_direct_storage.html
