### ISSUE TITLE
make github release consistent with pypi

### ISSUE THREAD

**Issue by hubutui** [huggingface/safetensors#351]
### Feature request

Hello, it seems that saftetesors in github repo use version tag like: x.y.z.rcw, and it's not consistent with pypi (x.y.zrcw). Could you make it consistent? And also mark it as a pre-release as described at [github doc](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) and pypi. Thanks!

### Motivation

None

### Your contribution

None

**Comment by hubutui** [comment]
just use `x.y.zrc1` instead of `x.y.rc1`. `x.y.rc1` is considered newer version than `x.y.z`, which is not right. Also use pre-release for a version like `x.y.zrc1` if it's not a release yet.

**Comment by Narsil** [comment]
I still fail to understand your issue.

Explain in detail behavior you're doing, what is happening and what you're expecting to happen.

**Comment by hubutui** [comment]
For example, in PyPI, you use version 0.3.3rc1 (https://pypi.org/project/safetensors/0.3.3rc1/), but in github you use 0.3.3.rc1 (https://github.com/huggingface/safetensors/releases/tag/v0.3.3.rc1).
It would be great to make these two the same.
Also, mark 0.3.3rc as pre-release as it's rc version, see also https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository.

**Comment by Narsil** [comment]
Oh the pre-release tag on GH is my bad.

No I don't see why I should align everything. Rust uses a different semver notations; https://users.rust-lang.org/t/alpha-beta-rc-with-cargo-semantic-versioning/69799/4
https://doc.rust-lang.org/cargo/reference/resolver.html#pre-releases

In general outside of releases I'll keep whatever makes my life easier.
As long as it's not breaking user's workflow in any major way (if you are running main all the time, you embrace the risks of any change we might want internally), I'll keep doing that.

For instance right now we have modified every version so that there's only 2 places where the version actually appears making it easier than before to do updates.

**Comment by hubutui** [comment]
cool, it also works for me if the pre-release tag on github is marked.
