### ISSUE TITLE
The default file format used when loading the model？

### ISSUE THREAD

**Issue by Kong-Aobo** [huggingface/safetensors#360]
I guess that huggingface loads .safetensor files by default when loading models. Is this mandatory? Can I choose to load files in. bin format? (Because I only downloaded weights in bin format, and it reported an error “ could not find a file in safeTensor format”). I do not find related infomation in docs.

Thanks for your help.

**Comment by Narsil** [comment]
You're not providing enough detalis for us to can help.

What are you doing, which script etc..

safetensors is not mandatory, but will become the default, we're making this change slow so everyone has time to adjust.
The only project that relies on safetensors is `text-generation-inference` which requires them because of TP sharding.
