### ISSUE TITLE
Stream load models (load model larger than system memory)

### ISSUE THREAD

**Issue by erikschul** [huggingface/safetensors#373]
### Feature request

I'm not very familiar with the details, but I'd like to load a 20GB model while having only 8 GB system memory.

Currently, safetensors loads the entire model into system memory.
Is it possible to load models incrementally/as a stream?

Related:
https://github.com/turboderp/exllama/issues/245
https://github.com/huggingface/safetensors/issues/67

Possibly related (writing is different from reading):
https://github.com/huggingface/safetensors/issues/291

### Motivation

Using swap requires unnecessary wear on SSDs. And it's silly to read a model from disk, just to write it back to disk as a swap, and then read it again from disk.

Alternatively, the model should be saved in a format that can be streamed directly to memory?

Similarly, it's silly to require X amount of system memory to be available for just a few seconds while loading a large model.

### Your contribution

Unqualified to contribute.

**Comment by Narsil** [comment]
Memory mapping is supposed to work as you expect.

Are you using Windows by any chance ? Or WSL ? Memory mapping seems quite subpar on those platforms (specially WSL).

There's absolutely no issue loading tensors 1 by 1 if needed, just adapt this code: https://gist.github.com/Narsil/3edeec2669a5e94e4707aa0f901d2282

It will be however atrociously slow (because reading from disk is atrociously slow).

**Comment by Narsil** [comment]
Turns out it's a `torch` thing:

```
storage = torch.UntypedStorage.from_file('example.txt', size=18000000)  # Whateve the size of the file is
```
This is used under the hood by safetensors in order to rely on torch to send the mapped buffers to cuda (this avoids the CPU allocation of the buffer, but does seem to cause the issue you are facing).

There are other ways to bypass torch allocation, but require using unsafe and reaching for torch packaged cuda librairies which is not ideal (hence why it was removed in 0.3.0).

**Comment by erikschul** [comment]
@Narsil Thanks. The domain is outside of my expertise. Would it be possible to implement this if `torch` had a specific API? What kind of API would be required (so I can post the issue on torch instead).

**Comment by Narsil** [comment]
The error is triggered here. https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/MapAllocator.cpp#L353

Reading it it seems to be caused by the unlink of the file, which I think they do mostly for Windows. Worth asking them definitely.
As a workaround , the code I linked above should be easy enough to adapt. @turboderp could probably do it.
The loss would be in terms of loading speed on the GPU, because it would force a CPU allocation before sending to the GPU.

With mmap you can say to cuda to copy from pointer X directly onto the GPU, making the CPU alloc seamless (and handled by the OS, making it potentially free, although not if you're loading something exceeding RAM anyway).
But because of torch internals, there's no way to call directly this copy function without using `UntypedStorage` (at least to the best of my knowledge).
Skipping torch internals, you can definitely call `mmap` yourself, create a CPU tensor from that (allocating only tensor per tensor), and sending it to the GPU afterwards.
