### ISSUE TITLE
Lazy file editing

### ISSUE THREAD

**Issue by vvvm23** [huggingface/safetensors#376]
### Feature request

Add the ability to edit files lazily. In other words, to be able to edit files without having to load all tensors and then rewrite.

### Motivation

Suppose we write a lot of embedding / model weights to disk, only to realise we forgot to save a particular tensor / saved the incorrect value / saved an extra tensor. This would require us rewriting the entire file(s) to update a single entry.

### Your contribution

I haven't wrote rust in a while, so probably not a good main contributor here. I did take a look at the header format and thought about a possible step by step approach. However, it only works if we have sufficient white space padding after the header, which isn't always present :/ 

But if we did, we could simply append the new tensor to the header dict and append the data to the byte array.

Would welcome contributions in the form of code / saying this isn't efficiently possible 🤗

**Comment by Narsil** [comment]
Hi @vvvm23,

This is trickier than it looks.
The reason is that there's usually little space between the header and the actual buffer storage, therefore if you add stuff in the header your have to move (at least the first) tensor all the way to the back, and rewrite this part of the header too (since location has changed).

However if you're  willing to open a PR I can definitely help you on the Rust part.

It's not impossible by anymeans but definitely inconvenient. I had plans to incorporate that directly in the lib to make distributed training workloads easier to work with, but it turns out it wasn't actually solving the problem (because most trainings use S3 or equivalent as a backstore to save weights and none of these distributed storage support partial uploads).

Another small workaround is to use multiple files, which might be a more immediate solution for you.

**Comment by vvvm23** [comment]
That's unfortuante how there isn't much room between the header and the main buffer. I think in that case it wouldn't be worth be adding the feature, as it is basically the same as creating a new file rather than extending the file in place.

I did end up using multiple files :)

**Comment by Narsil** [comment]
Closing this for now then.

I'm pretty sure most usage for this are actually by multiple files, without the headache, and offer in the end more flexibility (since opening, files, to load part of data is pretty much free)

**Comment by loodvn** [comment]
Another suggestion that could be useful (but probably out of scope) is allowing an index file? 
If you have the header info in a separate file you could append data to the data buffer and update offsets accordingly
