### ISSUE TITLE
[Feature request] How about support async save to disk?

### ISSUE THREAD

**Issue by ZHUI** [huggingface/safetensors#396]
### Feature request

How about support async save to disk?  

### Motivation

the weight or optimizer is vary large for LLMs，so，it will waste a lot of time for tensor from cpu to disk。
If we can support async save to disk, it will be vary helpful.

### Your contribution

.

**Comment by ZHUI** [comment]
@Narsil

**Comment by Narsil** [comment]
I don't think this lib should include async support directly (because of the size of the dependency it pulls and potential security holes it would open, not to mention the actual choice of async runtime).

You should probably be able to get away with async write by serializing into a raw buffer and doing async writes yourself, wouldn't that work ?
