### ISSUE TITLE
Zero copy saving

### ISSUE THREAD

**Issue by zeux** [huggingface/safetensors#415]
### Feature request

The library advertises the format as “zero-copy” - which it indeed is, for loading. Unfortunately, when saving models using safetensors.torch.save_file, the tensors get converted to bytes using numpy to_bytes method, which is expensive in terms of memory and performance. This most significantly affects model processing and conversion scripts. Would be nice if save_file was zero copy - I’d be happy to contribute a fix but I wanted to file an issue first ro understand the reasoning behind the current implementation.

### Motivation

This negatively affects efficiency of saving safetensor files.

### Your contribution

I can work on a PR for this.

**Comment by Narsil** [comment]
Hi @zeux Thanks a lot for the proposal.

It is true not a lot has been done for save performance, because it never has been a true bottleneck in the use cases I'm aware of.
Having some work on it, would mostly be welcome.

We cannot really change the Rust surface, not the Python API (so only the internals I think).
The reason for the numpy switch is that we do need to get the bytes onto the CPU before writing them to disc. There are no (to the best of the my knowledge) mecanisms to do that within frameworks like torch to actually write directly to disc (with something like gdrcopy).

The way it currently works, is that I need to access the raw buffers to write on disk with Rust.

One drawback with the current format is that you have to materialize all the tensors somewhere (VRAM or RAM) before writing them on disk too (you could imagine a lazy approach, but given that the header requires all file descriptions, and all data is written after the header, you do need to have all the header information, which usually involves materializing the tensors.

If you could try to motivate the use case (who is needing save speed and with which intents) it really helps frame a solution (There might be non code workaround which is something we have done in other projects).
Also I really like that currently most of the code is rather simple, so we should definitely keep that in mind.

**Comment by zeux** [comment]
Yeah - I understand that you need to copy the tensors if they are on the GPU side; however, the extra copy is performed by the `.bytes()` call. If you're using a Torch tensor then you can actually convert it (zero-copy I think?) to numpy via `.numpy()` and use numpy tofile to write the tensor directly completely in Python. I'm not necessarily suggesting this as a route to go - there might be reasons why you want to go through Rust, but it seems like maybe it would be possible to get the pointer to raw tensor bytes, and pass that to Rust directly?

I'm currently using a full Python implementation to work around this (as well as the lack of header alignment in the builtin code which helps use safetensors files directly from CPU code with aligned loads on tensor data). I've extracted this into a standalone benchmark that loads the tensors from disk, converts them to bf16, and writes them back: https://gist.github.com/zeux/b9b3019d0f410e07ec468a38b7aebc7c

Testing this on my system with the first of 3 of Llama 13B HF (fp16) files, and making sure to reset FS cache between every run (`echo 1 | sudo tee /proc/sys/vm/drop_caches`), I get:

```
$ python stbench.py model-00001-of-00003.safetensors test.st
load: 9.27 GiB, 2.026 sec,  4.91 GB/s
save: 9.27 GiB, 10.159 sec,  0.98 GB/s

$ python stbench.py model-00001-of-00003.safetensors test.st --fast
load: 9.27 GiB, 2.017 sec,  4.93 GB/s
save: 9.27 GiB, 7.405 sec,  1.34 GB/s

$ python stbench.py model-00001-of-00003.safetensors test.st --device cuda
load: 9.27 GiB, 9.962 sec,  1.00 GB/s
save: 9.27 GiB, 14.700 sec,  0.68 GB/s

$ python stbench.py model-00001-of-00003.safetensors test.st --device cuda --fast
load: 9.27 GiB, 9.286 sec,  1.07 GB/s
save: 9.27 GiB, 11.421 sec,  0.87 GB/s
```

So as you can see, there's a ~3 second cost for ~9 GB of data to copy these before saving, whether or not CUDA is involved. When using CUDA, the first load is actually really slow but this seems like a problem mostly on PyTorch side that I'm going to try to submit a fix for.

This is also given the fairly slow speed of writing the data due to the SSD used; using `/dev/null` as the output file, the raw cost becomes more apparent: without `--fast` I get 3.7 seconds of save time, with `--fast` I get 0 seconds as it's zero-copy.

I believe the time here is basically purely page fault handling by the kernel. It's possible that on server-grade systems with huge pages the cost is less substantial.

The above is an artificial benchmark; one of the real cases for example that I use is a script that converts fp16/bf16 source models to fp8 format; here's the timings I get on that script with a full Llama2 13B model (~26 GB read, ~13 GB written):

- cold FS cache, fast implementation: 16.4 seconds
- hot FS cache, fast implementation: 13.8 seconds
- cold FS cache, safetensors implementation: 21.7 seconds
- hot FS cache, safetensors implementation: 20.5 seconds

So one reason why I even went there in the first place was that the conversion was taking significantly longer than was comfortable. Another issue that I hit before is that when trying to work with large models (eg 70B), the fp8 output would be ~70 GB, but the script would need ~140 GB of RAM to perform the conversion because of the extra intermediate copy, and server hardware I was working with had ~128 GB RAM so the script didn't even run.

All of these aren't super critical in that they can be worked around with better hardware or just ignoring the extra cost and waiting a little longer for the save, but that's the motivation for this issue.

**Comment by Narsil** [comment]
> as well as the lack of header alignment in the builtin code which helps use safetensors files directly from CPU code with aligned loads on tensor data)

What do you mean, header is aligned, and checked for. Otherwise we wouldn´t  be able to load with zero-copy.

> the fp8 output would be ~70 GB, but the script would need ~140 GB of RAM to perform the conversion because of the extra intermediate copy, and server hardware I was working with had ~128 GB RAM so the script didn't even run.

Definitely seems to be the killer feature here, speed doesn't seem that bad (since everything is slowed by the SSD anyway).

Glad you found a way to workaround this. The rust is not technically needed for anything, but it does help providing security against out of bounds within the `get_slice` feature ( where you load only the part of the tensor you actually care for). The very first implementation had a subtle bug in it which would have lead to out of bounds, and rust would simply panic instead. Pretty big win imo.

But safetensors was designed to be as simple as possible do you could write most of it in pure python (or any language).
As for the unecessary copy, I've been waiting for this to happen :https://github.com/search?q=repo%3APyO3%2Fpyo3%20MemoryView&type=code (MemoryView) to be implemented in PyO3 so I could give a memory view to Rust instead of a PyBuffer (which does require a copy).

The other route is the one you have done where you directly instruct torch to write to a file handle, the only issue here is that it requires torch to have a such a surface which other vendors (tf/flax) do not have afaik, whereas memoryview compatibility would allow every framework to work)

**Comment by Nerogar** [comment]
Is this feature still planned? Having a zero copy save function would be really useful for situations where the model already fills most of the available ram. Unfortunately, the provided workaround has some downsides. It can't easily be used in code that's controlled by a third party library (for example the `save_pretrained()` function of the diffusers library). Also, any further changes to the safetensors library might require changes to this custom function.

**Comment by O-J1** [comment]
Following up on this as we still have users impacted by this and wondering if its actually not planned?
