### ISSUE TITLE
Convert OpenVINO to Safetensors

### ISSUE THREAD

**Issue by Micraow** [huggingface/safetensors#421]
### Feature request

To convert OpenVINO generated .bin model to safetensor

### Motivation

I converted a Stable Diffusion model to OpenVINO `.bin` model and performed an int8 quantization. But I want to use this quantized model in Stable-Diffusion-webui which doesn't accept OpenVINO model, so I hope you can provide a tool to convert.

### Your contribution

Maybe I can do some tests and if I am able to submit some code, I will.

**Comment by Narsil** [comment]
I don' t think I can provide any real help.

Most likely the issue is SD-webui not supporting the int8 tensors (and ops) you are mentionning (I could be mistaken haven' t looked at SD-webui nor OpenVINO in a long time). 

Safetensors is pretty agnostic to that kind of thing, saving tensors is really similar to PT, it's just not using Pickle which allows arbitrary code.

There' s a convertion script you can take a look at if you want.

```
weights = torch.load(filename)
save_file(weights, newfilename)
```
Is mostly it (in most cases).
