### ISSUE TITLE
Create C FFI to safetensors

### ISSUE THREAD

**Issue by KOLANICH** [huggingface/safetensors#72]

**Comment by Narsil** [comment]
PRs are welcome, but this might be very tedious since the main concern is security, ffi and ownership are probably going to be an issue. For PyO3 it definitely was a big pain. That's why the rust code part only uses references to the buffer, and never really the buffer itself. 

But the main idea, is that the spec of the file itself are so simple that implementing a reader should be dead trivial in any language, not necessarily binding to the rust part. Even the writer should not be too hard.

Having bindings becomes interesting only when we can leverage some of rust's guarantees, if we end up using unsafe everywhere then we're mostly loosing that and it would open unnecessary flaws.
I'd rather have several different/readable pieces of code than create messy bindings. 

For Python, I sincerely considered dropping Rust entirely at some point, but :
- Rust did prevent a real bug of reading out of bounds during development
- Rust makes it much easier to infer where things are copied and where they are not, and handle different `torch`/`tensorflow`/`jax` versions, which was starting to bloat the python code very fast (essentially lots of nested try..except everywhere, which are simple `Result` in Rust).
- It did enable the `SAFETENSORS_GPU_FAST` trick to call `cudaMemcpy` directly which I wouldn't know how to do in pure python.

The real fast loads on CPU are doable on pure pytorch: https://gist.github.com/Narsil/3edeec2669a5e94e4707aa0f901d2282
