### ISSUE TITLE
Running into "Some tensors share memory" `RuntimeError` when converting finetuned GPT2

### ISSUE THREAD

**Issue by mrshu** [huggingface/safetensors#98]
First of all, thanks a bunch for all your work on `safetensors` @Narsil (and HuggingFace for opensourcing it)!

I was keen to try it out in a very straightforward manner with a finetuned GPT2 model with the following script:

```python
from transformers import GPT2LMHeadModel, GPT2Tokenizer
gpt2_model = GPT2LMHeadModel.from_pretrained("./model")
gpt2_model.save_pretrained('./model-safetensor', safe_serialization=True)
```

Sadly, this resulted in the following `RuntimeError`:

```
  File "/Users/mrshu/Library/Caches/pypoetry/virtualenvs/gpt2-experiments-4HuXp8fp-py3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1619, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "/Users/mrshu/Library/Caches/pypoetry/virtualenvs/gpt2-experiments-4HuXp8fp-py3.8/lib/python3.8/site-packages/safetensors/torch.py", line 70, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/Users/mrshu/Library/Caches/pypoetry/virtualenvs/gpt2-experiments-4HuXp8fp-py3.8/lib/python3.8/site-packages/safetensors/torch.py", line 220, in _flatten
    raise RuntimeError(
RuntimeError: Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'lm_head.weight', 'transformer.wte.weight'}]
```

This was rather strange for me to run into, as my naive reading of the Docs (https://huggingface.co/docs/safetensors/speed) was that `gpt2` should be fairly straightforward to convert.

Can you see anything I might have done wrong? Could it be due to the fact that the model was originally serialized on an older version of `transformers`? I would appreciate any thoughts and suggestions you could spare.

Thanks!

--------- 

As the listing above suggests, this was tried on Python 3.8, with the following packages installed:

```
certifi==2022.9.24
charset-normalizer==2.1.1
filelock==3.8.0
huggingface-hub==0.11.0
idna==3.4
numpy==1.23.5
packaging==21.3
Pillow==9.3.0
pyparsing==3.0.9
PyYAML==6.0
regex==2022.10.31
requests==2.28.1
safetensors==0.2.4
tokenizers==0.13.2
torch==1.13.0
torchaudio==0.13.0
torchvision==0.14.0
tqdm==4.64.1
transformers==4.24.0
typing_extensions==4.4.0
urllib3==1.26.12
```

If there is any other piece of information I could provide that would help debug this issue, please let me know.

**Comment by Narsil** [comment]
Thank you @mrshu for reporting this,

The reason for this error is that is we need to update `transformers` code for that.

In PyTorch you can do:

```python
a = torch.zeros((2, 2))
b = a[:1, :]
torch.save({"a": a, "b": b})
```

And everything will work fine, and the tensors will be shared when loading the weights.
This is not possible in `safetensors` because it can lead to tricky issues where you allocate more than you need (when loading only "b" for instance, you will allocate the whole "a" tensor, and only slice into it). It also leads to more issues when doing things like distributed training/saving (where the weights cannot be shared).

You can use this script to convert existing weights: https://github.com/huggingface/safetensors/blob/main/bindings/python/convert.py . More specifically those lines: https://github.com/huggingface/safetensors/blob/main/bindings/python/convert.py#L91-L94
I'll open something in `transformers` to fix this. It's only a matter of skipping the `decoder.weight` weight while saving for it to work.

This won't cause any issues for `transformers` because the weight is automatically tied when you are loading with `AutoModel.from_pretrained(...)`. Meaning the tensors will be correctly shared.
